apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-vote-front
        image: diddyblink/azure-vote-front:v1
        imagePullPolicy: Always
#        volumeMounts:
 #   - mountPath: /my-nfs-data
  #    name: test-volume
#  volumes:
 # - name: test-volume
  #  nfs:
   #   server: my-nfs-server.example.com
    #  path: /my-nfs-volume
     # readOnly: true
        envFrom:
        - configMapRef:
            name: vote-values
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  ports:
  - port: 80
  selector:
    app: azure-vote-front
