apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-dev
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/diddyblink/azure-voting-app-redis.git
    targetRevision: Openshift_Argo  
    path: .                         
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app           
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true          