apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "crc-csi-hostpath-provisioner"
  nfs:
    server: 192.168.122.1     # L'IP della scheda di rete che utilizza l'host per parlare con la vm crc (virbr0)
    path: /var/nfs          # Il path nell'export list (definito nel nfs.config)
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "crc-csi-hostpath-provisioner"
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-pv-local

