apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: azure-vote-front
spec:
  to:
    kind: Service
    name: azure-vote-front  
    weight: 100
  port:
    targetPort: 80         
  wildcardPolicy: None
